version: '3.8'

services:
  web:
    container_name: testweb
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    container_name: testdb
    image: postgres:13.0-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuserpass
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"

volumes:
  postgresdata: